services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: project_management
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile  # assuming this Dockerfile is at the root
    container_name: project_dashboard_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: project_management
      DB_DIALECT: postgres
      NODE_ENV: development
      PORT: 5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    container_name: project_dashboard_frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  pgdata:
